name: Release

on:
  push:
    branches:
    - 'master'
    paths:
    - 'VERSION'

jobs:

  Release_Drafter:
    name: Release_Drafter
    runs-on: ubuntu-latest
    steps:

    - name: Release Drafter
      # You may pin to the exact commit or the version.
      # uses: release-drafter/release-drafter@06d4616a80cd7c09ea3cf12214165ad6c1859e67
      id: create_release
      uses: release-drafter/release-drafter@v5.11.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: set upload_url
      id: set_upload_url
      uses: noobly314/share-data@v1
      with:
        share-id: release_url
        mode: set
        key: url
        value: ${{ steps.create_release.outputs.upload_url }}

  u-build:
    name: build_ubuntu_go${{ matrix.go }}
    needs: Release_Drafter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18' ]
    steps:
    - name: Set up Go${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2
            
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install libgtk-3-dev libcairo2-dev libglib2.0-dev
        cd demo
        go build -v -buildmode=exe -tags 'gtk gtk_3_24' -o demo.run -i main.go
      
    - name: zip
      run: zip -q -r ubuntu_go${{ matrix.go }}.zip *
    
    - name: get upload_url
      id: get_upload_url
      uses: noobly314/share-data@v1
      with:
        share-id: release_url
        mode: get
        key: url

    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The URL for uploading assets to the release
        upload_url: ${{ steps.get_upload_url.outputs.data }}
        # The path to the asset you want to upload
        asset_path: ./ubuntu_go${{ matrix.go }}.zip
        # The name of the asset you want to upload
        asset_name: ubuntu_go${{ matrix.go }}.zip
        # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
        asset_content_type: application/zip

  w-build:
    name: build_windows_go${{ matrix.go }}
    needs: Release_Drafter
    runs-on: windows-latest
    strategy:
      matrix:
        go: [ '1.18' ]
    steps:
    - name: Set up Go${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd demo
        go build -v -buildmode=exe -o demo.exe -i main.go
        
    - name: zip
      run: .\7za.exe a -r .\windows_go${{ matrix.go }}.zip ./


    - name: get upload_url
      id: get_upload_url
      uses: noobly314/share-data@v1
      with:
        share-id: release_url
        mode: get
        key: url

    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The URL for uploading assets to the release
        upload_url: ${{ steps.get_upload_url.outputs.data }}
        # The path to the asset you want to upload
        asset_path: ./windows_go${{ matrix.go }}.zip
        # The name of the asset you want to upload
        asset_name: windows_go${{ matrix.go }}.zip
        # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
        asset_content_type: application/zip
