name: Test

on:
  push:
    branches:
    - '**'
    - '!master'

jobs:
  u-build:
    name: build_ubuntu_go${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.19' ]
    steps:
    - name: Set up Go${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install libgtk-3-dev libcairo2-dev libglib2.0-dev
        cd demo
        go get .
        go build -v -buildmode=exe -tags 'gtk gtk_3_24' -o demo.run -i main.go
      
    - name: zip
      run: zip -q -r ubuntu_go${{ matrix.go }}.zip *
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        path: ./ubuntu_go${{ matrix.go }}.zip
        
  w-build:
    name: build_windows_go${{ matrix.go }}
    runs-on: windows-latest
    strategy:
      matrix:
        go: [ '1.17', '1.18.0' ]
    steps:
    - name: Set up Go${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2
            
    - name: Build
      run: |
        cd demo
        go get .
        go build -v -buildmode=exe -o demo.exe -i main.go
        
    - name: zip
      run: .\7za.exe a -r .\windows_go${{ matrix.go }}.zip ./
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        path: ./windows_go${{ matrix.go }}.zip
